### ISSUE TITLE
Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by v-fcapra** [msLinuxNinja/sargraph#41]
Hello team,

I'm trying to open a sar file generated by SUSE supportconfig [(https://www.suse.com/c/basic-server-health-check-supportconfig/)](https://www.suse.com/c/basic-server-health-check-supportconfig/) but I got error "Cannot read properties of undefined (reading 'includes')"

Upon inspecting the sar file, it seems normal but some of the metrics seems to have extra columns, not sure if that affects the behavior of the tool.

I can provide more information if needed.

**Comment by msLinuxNinja** [comment]
Hey! Thanks for reporting this! What is the version of SLES?

**Comment by v-fcapra** [comment]
Version is SLES 15 SP3, Kernel is 5.3.18-150300.59.106.1

**Comment by msLinuxNinja** [comment]
Thanks! Let me do some testing, I recall having issues with SLES 15 files. Thanks again for reporting this

**Comment by msLinuxNinja** [comment]
Hey @v-fcapra  sorry for the super late reply, I tried a couple of SLES 15 sar files (SP2 and SP3) and both seem to work. Curious as to what is the version for the file you're trying to load?

Thanks!

**Comment by msLinuxNinja** [comment]
I was able to identify the issue, the problem seems to be missing disk section on certain SLES sar files, this would crash the app instead of simply showing a "no data found".

Fixed on #43
